server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    username: test
    password: 123456
    url: jdbc:oracle:thin:@localhost:1521:XE?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yiliu.sth.entity
